version: '3.7'
services:

  mariadb:
    image: mariadb:10.5
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: currency_converter
      MYSQL_USER: feature
      MYSQL_PASSWORD: secret
    volumes:
      - ./:/var/www/html/
    ports:
      - "3306:3306"
    networks:
      - currency_converter

  php:
    build:
      context: ./.docker/php/
    volumes:
      - ./:/var/www/html
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./.docker/php/conf.d/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
      - ./.docker/php/conf.d/max_execution_time.ini:/usr/local/etc/php/conf.d/max_execution_time.ini
      - ./.docker/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - currency_converter

  apache:
    build:
      context: ./.docker/apache2/
    depends_on:
      - php
    volumes:
      - ./:/var/www/html/
    ports:
      - '8000:80'
    networks:
      - currency_converter

networks:
  currency_converter:
    name: currency_converter
